<a href="https://colab.research.google.com/github/zeeshanchand/BigFivePersonalityTest/blob/main/twitter_gender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
df = pd.read_csv('/gender-classifier-DFE-791531.csv',
                encoding='latin1')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20050 entries, 0 to 20049
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   _unit_id               20050 non-null  int64  
 1   _golden                20050 non-null  bool   
 2   _unit_state            20050 non-null  object 
 3   _trusted_judgments     20050 non-null  int64  
 4   _last_judgment_at      20000 non-null  object 
 5   gender                 19953 non-null  object 
 6   gender:confidence      20024 non-null  float64
 7   profile_yn             20050 non-null  object 
 8   profile_yn:confidence  20050 non-null  float64
 9   created                20050 non-null  object 
 10  description            16306 non-null  object 
 11  fav_number             20050 non-null  int64  
 12  gender_gold            50 non-null     object 
 13  link_color             20050 non-null  object 
 14  name                   20050 non-null  object 
 15  pr

In [ ]:
pd.set_option('display.max_columns', None) # showing all columns without truncates
df.head(5)

_unit_id  _golden _unit_state  _trusted_judgments _last_judgment_at  \
0  815719226    False   finalized                   3    10/26/15 23:24   
1  815719227    False   finalized                   3    10/26/15 23:30   
2  815719228    False   finalized                   3    10/26/15 23:33   
3  815719229    False   finalized                   3    10/26/15 23:10   
4  815719230    False   finalized                   3     10/27/15 1:15   

   gender  gender:confidence profile_yn  profile_yn:confidence  \
0    male             1.0000        yes                    1.0   
1    male             1.0000        yes                    1.0   
2    male             0.6625        yes                    1.0   
3    male             1.0000        yes                    1.0   
4  female             1.0000        yes                    1.0   

          created                                        description  \
0    12/5/13 1:48                              i sing my own rhythm.   
1   10/1/12 13:51  I'm the author of novels filled with family dr...   
2  11/28/14 11:30                louis whining and squealing and all   
3   6/11/09 22:39  Mobile guy.  49ers, Shazam, Google, Kleiner Pe...   
4   4/16/14 13:23  Ricky Wilson The Best FRONTMAN/Kaiser Chiefs T...   

   fav_number gender_gold link_color            name profile_yn_gold  \
0           0         NaN     08C2C2         sheezy0             NaN   
1          68         NaN     0084B4     DavdBurnett             NaN   
2        7696         NaN     ABB8C2  lwtprettylaugh             NaN   
3         202         NaN     0084B4     douggarland             NaN   
4       37318         NaN     3B94D9    WilfordGemma             NaN   

                                        profileimage  retweet_count  \
0  https://pbs.twimg.com/profile_images/414342229...              0   
1  https://pbs.twimg.com/profile_images/539604221...              0   
2  https://pbs.twimg.com/profile_images/657330418...              1   
3  https://pbs.twimg.com/profile_images/259703936...              0   
4  https://pbs.twimg.com/profile_images/564094871...              0   

  sidebar_color                                               text  \
0        FFFFFF  Robbie E Responds To Critics After Win Against...   
1        C0DEED  ‰ÛÏIt felt like they were my friends and I was...   
2        C0DEED  i absolutely adore when louis starts the songs...   
3        C0DEED  Hi @JordanSpieth - Looking at the url - do you...   
4             0  Watching Neighbours on Sky+ catching up with t...   

  tweet_coord  tweet_count   tweet_created      tweet_id   tweet_location  \
0         NaN       110964  10/26/15 12:40  6.587300e+17  main; @Kan1shk3   
1         NaN         7471  10/26/15 12:40  6.587300e+17              NaN   
2         NaN         5617  10/26/15 12:40  6.587300e+17           clcncl   
3         NaN         1693  10/26/15 12:40  6.587300e+17    Palo Alto, CA   
4         NaN        31462  10/26/15 12:40  6.587300e+17              NaN   

                user_timezone  
0                     Chennai  
1  Eastern Time (US & Canada)  
2                    Belgrade  
3  Pacific Time (US & Canada)  
4                         NaN

In [ ]:
df.columns

Index(['_unit_id', '_golden', '_unit_state', '_trusted_judgments',
       '_last_judgment_at', 'gender', 'gender:confidence', 'profile_yn',
       'profile_yn:confidence', 'created', 'description', 'fav_number',
       'gender_gold', 'link_color', 'name', 'profile_yn_gold', 'profileimage',
       'retweet_count', 'sidebar_color', 'text', 'tweet_coord', 'tweet_count',
       'tweet_created', 'tweet_id', 'tweet_location', 'user_timezone'],
      dtype='object')

In [ ]:
# drop columns that irrelevant

col = ['gender', 'description', 'fav_number','link_color',
       'retweet_count', 'sidebar_color', 'text', 'tweet_count',
       ]

df = df[col]
df.sample(3)


gender                                        description  fav_number  \
16038  female  Vintage loving blogger. Communications. Public...        4274   
13724   brand  There is nothing that shows more strength than...        3265   
10773   brand  Chief Investment Officer of Astor Investment M...        2051   

      link_color  retweet_count sidebar_color  \
16038     E86FC6              0        FFFFFF   
13724     04A0C7              0             0   
10773     0084B4              0        C0DEED   

                                                    text  tweet_count  
16038  Absolutely delicious and indulgent dinner last...         8016  
13724  @chrisr249 you may love it and thats totally c...        18972  
10773  Getting a USS Lassen costume before they are a...         5603

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['fav_number'].plot(kind='hist', bins=20, title='fav_number')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['tweet_count'].plot(kind='hist', bins=20, title='tweet_count')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_3.groupby('gender').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('description').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_5.groupby('link_color').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_6.groupby('sidebar_color').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='index', y='fav_number', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8.plot(kind='scatter', x='fav_number', y='tweet_count', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['retweet_count']
  ys = series['index']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('retweet_count', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('gender')):
  _plot_series(series, series_name, i)
  fig.legend(title='gender', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('retweet_count')
_ = plt.ylabel('index')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['retweet_count']
  ys = series['index']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('retweet_count', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('description')):
  _plot_series(series, series_name, i)
  fig.legend(title='description', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('retweet_count')
_ = plt.ylabel('index')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['retweet_count']
  ys = series['index']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('retweet_count', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('link_color')):
  _plot_series(series, series_name, i)
  fig.legend(title='link_color', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('retweet_count')
_ = plt.ylabel('index')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['retweet_count']
  ys = series['index']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_12.sort_values('retweet_count', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('sidebar_color')):
  _plot_series(series, series_name, i)
  fig.legend(title='sidebar_color', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('retweet_count')
_ = plt.ylabel('index')

from matplotlib import pyplot as plt
_df_13['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_14['fav_number'].plot(kind='line', figsize=(8, 4), title='fav_number')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_15['tweet_count'].plot(kind='line', figsize=(8, 4), title='tweet_count')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['description'].value_counts()
    for x_label, grp in _df_16.groupby('gender')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('gender')
_ = plt.ylabel('description')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['link_color'].value_counts()
    for x_label, grp in _df_17.groupby('description')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('description')
_ = plt.ylabel('link_color')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['sidebar_color'].value_counts()
    for x_label, grp in _df_18.groupby('link_color')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('link_color')
_ = plt.ylabel('sidebar_color')

/usr/local/lib/python3.10/dist-packages/seaborn/utils.py:61: UserWarning: Glyph 141 (\x8d) missing from current font.
  fig.canvas.draw()
/usr/local/lib/python3.10/dist-packages/google/colab/_quickchart_lib.py:32: UserWarning: Glyph 141 (\x8d) missing from current font.
  plt.savefig(


from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['text'].value_counts()
    for x_label, grp in _df_19.groupby('sidebar_color')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('sidebar_color')
_ = plt.ylabel('text')

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_20['gender'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_20, x='index', y='gender', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_21['description'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_21, x='index', y='description', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_22['link_color'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_22, x='index', y='link_color', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_23['sidebar_color'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_23, x='index', y='sidebar_color', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
# see row that have missing value
df.isnull().sum()

gender             97
description      3744
fav_number          0
link_color          0
retweet_count       0
sidebar_color       0
text                0
tweet_count         0
dtype: int64

In [ ]:
# drop nan on columns gender
df = df.dropna(subset=['gender'])
df = df.dropna(subset=['description'])
df.sample(3)

gender                                        description  fav_number  \
12079  female   I love Jesus! IG: andrenaee | snapchat: andrenae        3018   
7568   female                           I luv breaking the rules           5   
9126    brand  News and Gossip from Inside TV Newsrooms and N...         495   

      link_color  retweet_count sidebar_color  \
12079     93A644              0        EEEEEE   
7568      0084B4              0        C0DEED   
9126      06249C              0        FFFFFF   

                                                    text  tweet_count  
12079  It's so hard to stay focus and motivated on a ...         4519  
7568            @toulousegrqnde you are the bestest _ÙÕÑ            3  
9126               What the..... https://t.co/nHy9aDNqsh        19265

from matplotlib import pyplot as plt
_df_24['fav_number'].plot(kind='hist', bins=20, title='fav_number')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_25['tweet_count'].plot(kind='hist', bins=20, title='tweet_count')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_26.groupby('gender').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_27.groupby('description').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_28.groupby('link_color').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_29.groupby('sidebar_color').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_30.plot(kind='scatter', x='fav_number', y='tweet_count', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['retweet_count']
  ys = series['fav_number']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_31.sort_values('retweet_count', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('gender')):
  _plot_series(series, series_name, i)
  fig.legend(title='gender', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('retweet_count')
_ = plt.ylabel('fav_number')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['retweet_count']
  ys = series['fav_number']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_32.sort_values('retweet_count', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('description')):
  _plot_series(series, series_name, i)
  fig.legend(title='description', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('retweet_count')
_ = plt.ylabel('fav_number')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['retweet_count']
  ys = series['fav_number']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_33.sort_values('retweet_count', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('link_color')):
  _plot_series(series, series_name, i)
  fig.legend(title='link_color', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('retweet_count')
_ = plt.ylabel('fav_number')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['retweet_count']
  ys = series['fav_number']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_34.sort_values('retweet_count', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('sidebar_color')):
  _plot_series(series, series_name, i)
  fig.legend(title='sidebar_color', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('retweet_count')
_ = plt.ylabel('fav_number')

from matplotlib import pyplot as plt
_df_35['fav_number'].plot(kind='line', figsize=(8, 4), title='fav_number')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_36['tweet_count'].plot(kind='line', figsize=(8, 4), title='tweet_count')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['description'].value_counts()
    for x_label, grp in _df_37.groupby('gender')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('gender')
_ = plt.ylabel('description')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['link_color'].value_counts()
    for x_label, grp in _df_38.groupby('description')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('description')
_ = plt.ylabel('link_color')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['sidebar_color'].value_counts()
    for x_label, grp in _df_39.groupby('link_color')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('link_color')
_ = plt.ylabel('sidebar_color')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['text'].value_counts()
    for x_label, grp in _df_40.groupby('sidebar_color')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('sidebar_color')
_ = plt.ylabel('text')

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_41['gender'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_41, x='fav_number', y='gender', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_42['description'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_42, x='fav_number', y='description', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_43['link_color'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_43, x='fav_number', y='link_color', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_44['sidebar_color'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_44, x='fav_number', y='sidebar_color', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
# drop column gender which is unknown

mask = df['gender'] == 'unknown'
df = df[~mask]
df = df.reset_index(drop=True)

In [ ]:
df.isnull().sum() # no nan row, our data is clean

gender           0
description      0
fav_number       0
link_color       0
retweet_count    0
sidebar_color    0
text             0
tweet_count      0
dtype: int64

In [ ]:
# change male=>0, female=>1, brand=>2
df.loc[df['gender'] == 'male', 'gender'] = 0
df.loc[df['gender'] == 'female', 'gender'] = 1
df.loc[df['gender'] == 'brand', 'gender'] = 2

df

gender                                        description  fav_number  \
0          0                              i sing my own rhythm.           0   
1          0  I'm the author of novels filled with family dr...          68   
2          0                louis whining and squealing and all        7696   
3          0  Mobile guy.  49ers, Shazam, Google, Kleiner Pe...         202   
4          1  Ricky Wilson The Best FRONTMAN/Kaiser Chiefs T...       37318   
...      ...                                                ...         ...   
15517      1                                               (rp)         302   
15518      0  Whatever you like, it's not a problem at all. ...        2513   
15519      0  #TeamBarcelona ..You look lost so you should f...          50   
15520      1  Anti-statist; I homeschool my kids. Aspiring t...       70804   
15521      1                     Teamwork makes the dream work.        3348   

      link_color  retweet_count sidebar_color  \
0         08C2C2              0        FFFFFF   
1         0084B4              0        C0DEED   
2         ABB8C2              1        C0DEED   
3         0084B4              0        C0DEED   
4         3B94D9              0             0   
...          ...            ...           ...   
15517     0084B4              0        C0DEED   
15518     CFB929              0             0   
15519     0084B4              0        C0DEED   
15520     9266CC              0             0   
15521     0084B4              0        C0DEED   

                                                    text  tweet_count  
0      Robbie E Responds To Critics After Win Against...       110964  
1      ‰ÛÏIt felt like they were my friends and I was...         7471  
2      i absolutely adore when louis starts the songs...         5617  
3      Hi @JordanSpieth - Looking at the url - do you...         1693  
4      Watching Neighbours on Sky+ catching up with t...        31462  
...                                                  ...          ...  
15517  @lookupondeath ...Fine, and I'll drink tea too...          783  
15518  Greg Hardy you a good player and all but don't...        13523  
15519  You can miss people and still never want to se...        26419  
15520  @bitemyapp i had noticed your tendency to pee ...        56073  
15521  I think for my APUSH creative project I'm goin...         2922  

[15522 rows x 8 columns]

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
df_status = df.copy()
df_status = pd.concat([df_status['gender'], df_status['description']], axis=1)

df_status

gender                                        description
0          0                              i sing my own rhythm.
1          0  I'm the author of novels filled with family dr...
2          0                louis whining and squealing and all
3          0  Mobile guy.  49ers, Shazam, Google, Kleiner Pe...
4          1  Ricky Wilson The Best FRONTMAN/Kaiser Chiefs T...
...      ...                                                ...
15517      1                                               (rp)
15518      0  Whatever you like, it's not a problem at all. ...
15519      0  #TeamBarcelona ..You look lost so you should f...
15520      1  Anti-statist; I homeschool my kids. Aspiring t...
15521      1                     Teamwork makes the dream work.

[15522 rows x 2 columns]

from matplotlib import pyplot as plt
import seaborn as sns
df_status.groupby('gender').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

In [ ]:
# make all lowercase since "Run" is not the same as "run" for machine computation
import re

description = []

for x in df_status['description']:
    desc = re.sub("[^a-zA-Z]"," ",x)
    desc = desc.lower()
    description.append(desc)

df_status['description'] = description
df_status

gender                                        description
0          0                              i sing my own rhythm 
1          0  i m the author of novels filled with family dr...
2          0                louis whining and squealing and all
3          0  mobile guy     ers  shazam  google  kleiner pe...
4          1  ricky wilson the best frontman kaiser chiefs t...
...      ...                                                ...
15517      1                                                rp 
15518      0  whatever you like  it s not a problem at all  ...
15519      0   teambarcelona   you look lost so you should f...
15520      1  anti statist  i homeschool my kids  aspiring t...
15521      1                     teamwork makes the dream work 

[15522 rows x 2 columns]

from matplotlib import pyplot as plt
import seaborn as sns
df_status.groupby('gender').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

In [ ]:
# remove stopwords in sentence ==> i,a,the,an,and,.,me,........
def remove_stopwords(text):
    words = nltk.word_tokenize(text)
    stop_words = set(stopwords.words('english'))
    filtered_words = [word for word in words if word.lower() not in stop_words]
    return filtered_words


df_status['tokenized'] = df_status['description'].apply(remove_stopwords)
df_status

gender                                        description  \
0          0                              i sing my own rhythm    
1          0  i m the author of novels filled with family dr...   
2          0                louis whining and squealing and all   
3          0  mobile guy     ers  shazam  google  kleiner pe...   
4          1  ricky wilson the best frontman kaiser chiefs t...   
...      ...                                                ...   
15517      1                                                rp    
15518      0  whatever you like  it s not a problem at all  ...   
15519      0   teambarcelona   you look lost so you should f...   
15520      1  anti statist  i homeschool my kids  aspiring t...   
15521      1                     teamwork makes the dream work    

                                               tokenized  
0                                         [sing, rhythm]  
1       [author, novels, filled, family, drama, romance]  
2                            [louis, whining, squealing]  
3      [mobile, guy, ers, shazam, google, kleiner, pe...  
4      [ricky, wilson, best, frontman, kaiser, chiefs...  
...                                                  ...  
15517                                               [rp]  
15518  [whatever, like, problem, chargernation, forev...  
15519  [teambarcelona, look, lost, follow, follow, he...  
15520  [anti, statist, homeschool, kids, aspiring, th...  
15521                     [teamwork, makes, dream, work]  

[15522 rows x 3 columns]

In [ ]:
pip install nltk

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
# count word in sentence by changing tokenized to vectorizor (for machine compute)
# CountVectorizer input must be string with one long list

from sklearn.feature_extraction.text import CountVectorizer

max_features = 1500
corpus = [' '.join(words) for words in df_status['tokenized']]

vectorizer = CountVectorizer(max_features = max_features, stop_words = "english")
X = vectorizer.fit_transform(corpus).toarray()

# let's see X in dataframe
df_ = pd.DataFrame(X, columns=vectorizer.get_feature_names_out(), index=df_status.index)

df_

academy  account  achieve  act  action  active  activist  actor  \
0            0        0        0    0       0       0         0      0   
1            0        0        0    0       0       0         0      0   
2            0        0        0    0       0       0         0      0   
3            0        0        0    0       0       0         0      0   
4            0        0        0    0       0       0         0      0   
...        ...      ...      ...  ...     ...     ...       ...    ...   
15517        0        0        0    0       0       0         0      0   
15518        0        0        0    0       0       0         0      0   
15519        0        0        0    0       0       0         0      0   
15520        0        0        0    0       0       0         0      0   
15521        0        0        0    0       0       0         0      0   

       actress  actually  add  addict  addicted  admin  adult  adventure  \
0            0         0    0       0         0      0      0          0   
1            0         0    0       0         0      0      0          0   
2            0         0    0       0         0      0      0          0   
3            0         0    0       0         0      0      0          0   
4            0         0    0       0         0      0      0          0   
...        ...       ...  ...     ...       ...    ...    ...        ...   
15517        0         0    0       0         0      0      0          0   
15518        0         0    0       0         0      0      0          0   
15519        0         0    0       0         0      0      0          0   
15520        0         0    0       0         0      0      0          0   
15521        0         0    0       0         0      0      0          0   

       adventures  advertising  advice  advisor  advocate  af  affairs  \
0               0            0       0        0         0   0        0   
1               0            0       0        0         0   0        0   
2               0            0       0        0         0   0        0   
3               0            0       0        0         0   0        0   
4               0            0       0        0         0   0        0   
...           ...          ...     ...      ...       ...  ..      ...   
15517           0            0       0        0         0   0        0   
15518           0            0       0        0         0   0        0   
15519           0            0       0        0         0   0        0   
15520           0            0       0        0         0   0        0   
15521           0            0       0        0         0   0        0   

       affiliate  affiliated  aficionado  afraid  africa  african  age  \
0              0           0           0       0       0        0    0   
1              0           0           0       0       0        0    0   
2              0           0           0       0       0        0    0   
3              0           0           0       0       0        0    0   
4              0           0           0       0       0        0    0   
...          ...         ...         ...     ...     ...      ...  ...   
15517          0           0           0       0       0        0    0   
15518          0           0           0       0       0        0    0   
15519          0           0           0       0       0        0    0   
15520          0           0           0       0       0        0    0   
15521          0           0           0       0       0        0    0   

       agency  agent  air  aka  al  alive  alternative  alum  alumni  amateur  \
0           0      0    0    0   0      0            0     0       0        0   
1           0      0    0    0   0      0            0     0       0        0   
2           0      0    0    0   0      0            0     0       0        0   
3           0      0    1    0   0      0            0     0       0        0   
4           0      0  

In [ ]:
# it is array
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
y = df.iloc[:,0].values # make it to array
y # gender ==> our target in the model

array([0, 0, 0, ..., 0, 1, 1], dtype=object)

In [ ]:
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Convert data into DMatrix format, which is the format that XGBoost expects
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

# Define XGBoost parameters
params = {
    'objective': 'multi:softmax',  # Specify the objective for multi-class classification
    'num_class': len(np.unique(y_train)),  # Number of classes
    'max_depth': 3,  # Maximum tree depth
    'eta': 0.1,  # Learning rate
    'subsample': 0.8,  # Fraction of samples used for training each tree
    'colsample_bytree': 0.8,  # Fraction of features used for training each tree
    'eval_metric': 'mlogloss'  # Evaluation metric
}

# Train the XGBoost model
num_round = 100  # Number of boosting rounds
bst = xgb.train(params, dtrain, num_round)

# Make predictions on the test set
y_pred = bst.predict(dtest)

In [ ]:
# Calculate accuracy
accuracy = accuracy_score(y_test.tolist(), y_pred.tolist())

print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.55


In [ ]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix

# Calculate the confusion matrix
conf_matrix = confusion_matrix(y_test.tolist(), y_pred.tolist())

# Print the confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[ 326  655   76]
 [ 125 1023   44]
 [  87  423  346]]


In [ ]:
# Generate the classification report
report = classification_report(y_test.tolist(), y_pred.tolist())

# Print the classification report
print("XGBoost Classification Report:\n", report)

XGBoost Classification Report:
               precision    recall  f1-score   support

           0       0.61      0.31      0.41      1057
           1       0.49      0.86      0.62      1192
           2       0.74      0.40      0.52       856

    accuracy                           0.55      3105
   macro avg       0.61      0.52      0.52      3105
weighted avg       0.60      0.55      0.52      3105



In [ ]:
from sklearn.naive_bayes import GaussianNB

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# change y_train, y_test dtype from object to int64
y_train = y_train.astype(np.int64)
y_test = y_test.astype(np.int64)

# Create a Naive Bayes classifier (Gaussian Naive Bayes)
nb_classifier = GaussianNB()

# Fit the classifier to the training data
nb_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred = nb_classifier.predict(X_test)

In [ ]:
# Calculate the accuracy of the NB Classifier
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.56


In [ ]:
# Confusion Matrix

# Calculate the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[326 605 126]
 [138 928 126]
 [101 265 490]]


In [ ]:
# Generate the classification report
report = classification_report(y_test, y_pred)

# Print the classification report
print("Naive Bayes Classification Report:\n", report)

Naive Bayes Classification Report:
               precision    recall  f1-score   support

           0       0.58      0.31      0.40      1057
           1       0.52      0.78      0.62      1192
           2       0.66      0.57      0.61       856

    accuracy                           0.56      3105
   macro avg       0.58      0.55      0.55      3105
weighted avg       0.58      0.56      0.54      3105



In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# change y_train, y_test dtype from object to int64
y_train = y_train.astype(np.int64)
y_test = y_test.astype(np.int64)

# Create a Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to the training data
rf_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred = rf_classifier.predict(X_test)


In [ ]:
# Calculate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.58


In [ ]:
# Confusion Matrix

# Calculate the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[495 400 162]
 [291 755 146]
 [132 188 536]]


In [ ]:
# Generate the classification report
report = classification_report(y_test, y_pred)

# Print the classification report
print("Random Forest Classification Report:\n", report)

Random Forest Classification Report:
               precision    recall  f1-score   support

           0       0.54      0.47      0.50      1057
           1       0.56      0.63      0.60      1192
           2       0.64      0.63      0.63       856

    accuracy                           0.58      3105
   macro avg       0.58      0.58      0.58      3105
weighted avg       0.57      0.58      0.57      3105



In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# change y_train, y_test dtype from object to int64
y_train = y_train.astype(np.int64)
y_test = y_test.astype(np.int64)

# Create a Decision Tree Classifier
dt_classifier = DecisionTreeClassifier(random_state=42)

# Fit the classifier to the training data
dt_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred = dt_classifier.predict(X_test)

In [ ]:
# Calculate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.54


In [ ]:
# Confusion Matrix

# Calculate the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[478 414 165]
 [306 730 156]
 [171 218 467]]


In [ ]:
# Generate the classification report
report = classification_report(y_test, y_pred)

# Print the classification report
print("Decision Tree Classification Report:\n", report)

Decision Tree Classification Report:
               precision    recall  f1-score   support

           0       0.50      0.45      0.48      1057
           1       0.54      0.61      0.57      1192
           2       0.59      0.55      0.57       856

    accuracy                           0.54      3105
   macro avg       0.54      0.54      0.54      3105
weighted avg       0.54      0.54      0.54      3105

